[connections.snowflake]
account = "ADPJSPU-CLB58914"  # e.g., xy12345.us-east-1
user = "Tikay"
password = "Voxushustech12#"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
